Revert "a"

diff --git a/.github/workflows/version.yml b/.github/workflows/version.yml
--- a/.github/workflows/version.yml
+++ b/.github/workflows/version.yml
@@ -17,6 +17,43 @@ jobs:
     - name: Set up Dart
       uses: dart-lang/setup-dart@v1
 
+    - name: Validate files
+      run: |
+        # Extract version from pubspec.yaml
+        version=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2)
+
+        # Get the version from the last commit on release (if it exists)
+        git fetch origin release
+
+        # Get the version from the fetched release branch
+        last_version=$(git show FETCH_HEAD:pubspec.yaml | grep 'version:' | cut -d ' ' -f 2)
+
+        # Check if the versions are different
+        if [ "$version" != "$last_version" ]; then
+          echo "Version has been updated to $version"
+        else
+          echo "Version has not been updated. Current version: $version. Last version: $last_version"
+          exit 1
+        fi
+
+        # Check if README.md and CHANGELOG.md contain the new version number
+        if grep -q "$version" README.md && grep -q "$version" CHANGELOG.md; then
+          echo "Version number found in README.md and CHANGELOG.md"
+        else
+          if grep -q "$version" README.md; then
+            echo "Version number found in README.md"
+          else
+            echo "Version number not found in README.md"
+          fi
+
+          if grep -q "$version" CHANGELOG.md; then
+            echo "Version number found in CHANGELOG.md"
+          else
+            echo "Version number not found in CHANGELOG.md"
+          fi
+          exit 1
+        fi
+
     - name: Generate tag message
       id: generate_tag_message
       env:
